server:
    port: 9009

spring:
    application:
        name: MoneyTransferPoints
    jpa:
        show-sql: true
        hibernate.ddl-auto: none
        properties.hibernate.format_sql: true
        properties.hibernate.ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
---
spring:
    profiles: test
    jpa:
        database: oracle
        show-sql: true
    datasource:
        platform: oracle
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: ss
        password: ss